library(shiny)
library(RJSONIO)
library(RMySQL)
library(XML)
library(wordcloud)
library(RCurl)
options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))
require(mallet)